[grid]
hidden_dim = [128, 256, 512]
# hidden_dim_gated = [128, 256, 512]
num_transformer_heads = [2, 4, 8]
tr_layer_number = [1, 2, 3]
# out_features= [128, 256, 512]
# num_graph_heads = [2, 4, 8]

[defaults]
hidden_dim = 128
# hidden_dim_gated = 128
num_transformer_heads = 2
tr_layer_number = 1
# out_features = 128
# num_graph_heads = 2
